import test from 'node:test';
import assert from 'node:assert/strict';
import {createNewGameState} from '../js/main/state.js?v=77';
import {advanceGameWeek,getTournamentEventsForDate} from '../data/game-data.js?v=77';
import {createTournamentEntryData} from '../js/main/tournament-bridge.js?v=77';
import {calculateTournamentRuntimeChecksum,createTournamentRuntime,createTournamentResumeData,validateTournamentResumeDataForEntry} from '../js/tournament/runtime.js?v=77';
import {beginLiveBattleToDraft,updateLiveBattleToDraft} from '../js/tournament/battle-core.js?v=77';
import {getUsableReadySkills,applyBattleDamage} from '../js/tournament/battle-actions.js?v=77';
import {convertLegacyGrowthToDiamonds,trainingReward} from '../data/simple-growth.js?v=77';
import {saveAutoEquipment} from '../js/main/auto-equipment.js?v=77';
import {purchaseConsumableToDraft,executeTrainingToDraft} from '../js/main/management.js?v=77';
import {calculatePlayerStatUpgradePlan,applyPlayerStatUpgradePlanToDraft} from '../js/main/team.js?v=77';
function fresh(){return structuredClone(createNewGameState({companyBaseName:'検証',playerNames:{IGL:'ミライ',ATK:'レン',SUP:'ヒカリ'}}));}
function fixture(){const state=fresh();state.inventory.items={pb2_gummy:1,spin_knit:1,scope:1};saveAutoEquipment(state,['pb2_gummy','spin_knit','scope']);let event;for(let i=0;i<48&&!event;i++){event=getTournamentEventsForDate(state.gameDate).find(e=>e.tournamentType==='local');if(!event)state.gameDate=structuredClone(advanceGameWeek(state.gameDate));}const entry=createTournamentEntryData(state,event),runtime=structuredClone(createTournamentRuntime(entry));runtime.match=1;runtime.round=2;runtime.currentOpponentId=runtime.teams.find(t=>t.teamId!==runtime.playerTeamId).teamId;runtime.phase='BATTLE';return {state,entry,runtime};}
test('legacy points become shared diamonds once, without deleting inventory',()=>{const s=fresh();s.inventory.items.scope=3;s.playerTrainingPoints[s.playerTeam.members[0].playerId]={power:20,tech:20,mental:20,shoot:20};const before=s.resources.diamond;assert.equal(convertLegacyGrowthToDiamonds(s),20);assert.equal(s.resources.diamond,before+20);assert.equal(convertLegacyGrowthToDiamonds(s),0);assert.equal(s.inventory.items.scope,3);});
test('training rewards are previewable and coins cannot go negative',()=>{const s=fresh();s.records.trainingCompleted=3;assert.equal(trainingReward(s,'balanced_training').total,50);s.resources.coin=0;const before=structuredClone(s);assert.throws(()=>executeTrainingToDraft(s,s.playerTeam.members.map(p=>({playerId:p.playerId,programId:'combat_drill'}))),/コイン/);assert.equal(s.resources.coin,0);assert.deepEqual(s.gameDate,before.gameDate);});
test('diamond upgrades reject an unaffordable batch without partially upgrading',()=>{const s=fresh(),id=s.playerTeam.members[0].playerId;s.resources.diamond=1;const before=structuredClone(s);assert.equal(calculatePlayerStatUpgradePlan(s,id,{aim:3}).affordable,false);assert.throws(()=>applyPlayerStatUpgradePlanToDraft(s,id,{aim:3}),/ダイヤ/);assert.deepEqual(s,before);});
test('manual combat never auto-casts player skills, even on downs',()=>{const {runtime}=fixture();beginLiveBattleToDraft(runtime);for(let i=0;i<110&&!runtime.lastBattleResult;i++)updateLiveBattleToDraft(runtime);assert.ok(runtime.lastBattleResult);assert.equal(runtime.lastBattleEvents.filter(e=>e.type==='skill_cutin'&&e.actorTeamId===runtime.playerTeamId).length,0);});
test('downed players have a rescue window before a follow-up bullet confirms the kill',()=>{const {runtime}=fixture();beginLiveBattleToDraft(runtime);const b=runtime.activeBattle,all=Object.values(b.participants),target=all.find(p=>p.teamId===b.leftTeamId),actor=all.find(p=>p.teamId===b.rightTeamId);target.combatState='down';target.hp=0;target.downedAt=b.elapsedSeconds;const result=applyBattleDamage(b,actor,target,100);assert.equal(result.reason,'revive_window');assert.equal(target.combatState,'down');});
test('shop purchase and per-player equipment enforce stock and coin cost',()=>{const s=fresh(),coin=s.resources.coin;purchaseConsumableToDraft(s,'pb2_gummy',2);assert.equal(s.resources.coin,coin-1200);assert.equal(s.inventory.items.pb2_gummy,2);assert.throws(()=>saveAutoEquipment(s,['pb2_gummy','pb2_gummy','pb2_gummy']),/所持数/);saveAutoEquipment(s,['pb2_gummy','pb2_gummy','']);assert.deepEqual(s.inventory.carryBag.slots.slice(0,3),['pb2_gummy','pb2_gummy',null]);});
test('manual skills wait for taps and consume CT on the actual engine',()=>{const {runtime}=fixture();beginLiveBattleToDraft(runtime);const own=Object.values(runtime.activeBattle.participants).filter(p=>p.teamId===runtime.playerTeamId);let choice;for(let i=0;i<60&&!choice&&!runtime.lastBattleResult;i++){updateLiveBattleToDraft(runtime);if(runtime.activeBattle){for(const p of Object.values(runtime.activeBattle.participants).filter(p=>p.teamId===runtime.playerTeamId)){const skill=getUsableReadySkills(runtime.activeBattle,p)[0];if(skill){choice={playerId:p.playerId,skillId:skill.skillId};break;}}}}
 assert.ok(choice,'a living player has a ready skill');assert.equal(runtime.activeBattle.events.filter(e=>e.type==='skill_cutin'&&e.actorTeamId===runtime.playerTeamId).length,0);const tick=runtime.activeBattle.tickCount;updateLiveBattleToDraft(runtime,{...choice,tick:false});assert.equal(runtime.activeBattle.tickCount,tick,'tap queues without accelerating time');updateLiveBattleToDraft(runtime);const events=runtime.activeBattle?.events??runtime.lastBattleEvents;assert.ok(events.some(e=>e.type==='skill_cutin'&&e.actorPlayerId===choice.playerId&&e.skillId===choice.skillId));if(runtime.activeBattle)assert.ok(!getUsableReadySkills(runtime.activeBattle,runtime.activeBattle.participants[choice.playerId]).some(s=>s.skillId===choice.skillId));
});
test('automatic items consume once, persist through checkpoints, and battle finalizes once',()=>{const {runtime,entry}=fixture();beginLiveBattleToDraft(runtime);updateLiveBattleToDraft(runtime,{autoSkills:true});assert.equal(runtime.inventory.consumedCarryItems.spin_knit,1);assert.equal(runtime.inventory.consumedCarryItems.scope,1);assert.equal(runtime.inventory.consumedCarryItems.pb2_gummy,undefined);runtime.runtimeChecksum=calculateTournamentRuntimeChecksum(runtime);const resume=createTournamentResumeData(runtime);validateTournamentResumeDataForEntry(resume,entry);let iterations=0;while(!runtime.lastBattleResult&&iterations++<110)updateLiveBattleToDraft(runtime);assert.ok(runtime.lastBattleResult);assert.ok(iterations<=101);assert.equal(runtime.inventory.consumedCarryItems.spin_knit,1);assert.ok((runtime.inventory.consumedCarryItems.pb2_gummy??0)<=1);const before=structuredClone(runtime);updateLiveBattleToDraft(runtime);assert.deepEqual(runtime,before);});


